config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts
  resources :users, only: [] do   
    resources :answers, only: [:new, :create]
    namespace :admin do
      resources :answers, only: [:show, :destroy]
    end
  end
  
  resource :answers, only: [:show]
  namespace :admin do
    resources :answers, only: [:index]
    resources :users, only: [:index, :show]
  end
  
  post 'answers' => 'answers#show'
  
  devise_for :users
  
  # ログインページをルートパスにする
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  
  with_options presence: true do
    validates :a1
    validates :a2
    validates :a3
    validates :a4
    validates :a5
    validates :a6
    validates :a7
  end
  
  # validates_uniqueness_of :sub_id, :scope => :user_id

  # before_create do
  #   this.sub_id = user.answers.size + 1
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:id]
  
  has_many :answers
         
  def email_required?
    false
  end

  def email_changed?
    false
  end
  
  # エラー解除のため
  def will_save_change_to_email?
    false
  end
  
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < ApplicationController
  before_action :if_not_admin
  # before_action :set_answers, only: [:index, :edit, :destroy]
  def index
    # @answers = Answer.includes(:user).order(created_at: :desc)
    @answers = Answer.page(params[:page]).reverse_order
  end
  
  def show
    @answers = Answer.includes(:user).order(created_at: :desc)
    @answer = @answers.find_by(id: params[:id])
    latest_answer_id = params[:id].to_i
    @user = User.find_by("id = ?", @answer.user_id)
    @pre_answer = @user.answers.where("id < ?", latest_answer_id).last

    # 質問項目の要約文を配列へ格納
    @questions = ['目の疲れ', '口内炎', '下痢', '歯茎の出血', '気分', '胃もたれ', '尿頻度']
    #  answersテーブルのカラム名を配列へ格納
    @answer_keys = ['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7']
  end
  
  def destroy
    answer = Answer.find_by(id: params[:id])
    answer.destroy
    redirect_to admin_user_path(answer.user_id)
    flash[:success] = "1件削除しました。"
  end
  
  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
  
  # def set_answers
  #   @answers = Answer.includes(:user).order(created_at: :desc)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @answer = Answer.new
    @user = User.find_by(id: current_user.id)
  end
  
  def create
    @answer = current_user.answers.new(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to answers_path
    else
      @user = User.find_by(id: params[:id])
    render 'answers/new', user_id: @answer.user_id
    end
  end
  
  def show
    flash[:success] = "回答が保存されました"
  end
  
  private
  def answer_params
    params.permit(:a1, :a2, :a3, :a4, :a5, :a6, :a7)
    # :a8, :a9, :a10, :a11, :a12, :a13, :a14, :a15, :a16, :a17, :a18, :a19, :a20
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインしていないユーザーはログインページへ遷移。deviseを使用するときは許可されたparamsのみ受け取る。
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # CSRF(クロスサイトリクエストフォージェリ)対策
  protect_from_forgery with: :exception
  
  
  # ログイン後遷移ページをオーバーライド。管理者なら回答一覧、一般ユーザーなら新規回答画面へ遷移。
  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_answers_path
    else
      new_user_answer_path(user_id: current_user.id)
    end
  end
  
  
  #　ログイン認証にid使用することを許可 
  protected
  def configure_permitted_parameters
    added_attrs = [:id, :last_name, :first_name]
    devise_parameter_sanitizer.permit(:sign_in, keys: [:id])
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/answers_helper.rb
module Admin::AnswersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/answers/index.html.erb
<div class="col-md-6 offset-md-2 ">
<h5>回答一覧</h5>
  <table class="table table-striped table-hover">
    <thead class="thead-light">
      <tr>
        <th>患者ID</th>
        <th>氏名</th>
        <th>回答日時</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user_id %></td>
        <td><%= link_to (answer.user.last_name + "　" + answer.user.first_name), admin_user_path(answer.user_id) %></td>
        <td>
          <%= link_to user_admin_answer_path(answer.user_id, answer) do %>
            <%= answer.created_at.strftime('%Y/%m/%d  %H:%M') %>
          <% end %>
        </td>
        <td>
          <%= link_to '削除', user_admin_answer_path(answer.user_id, answer), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-sm" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @answers %>
</div> 

app/views/admin/answers/show.html.erb
<div class="col-md-6 offset-md-2">
<h5>回答詳細</h5>

<%= link_to admin_user_path(@user) do %>
  <h6>患者ID：<span><%= @user.id %></span></h6>
  <h6>氏　名：<span><%= @user.last_name + " " + @user.first_name %></span></h6>
<% end %>

  <table class="table">
    <thead>
      <tr><th>項目</th><th>&nbsp&nbsp回答</th><th>&nbsp&nbsp以前の回答</th><th></th></tr>
    </thead>
  
    <tbody>
      <tr>
        <td>回答日</td>
        <td>&nbsp&nbsp
          <%= @answer.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
        <% if @pre_answer %>&nbsp&nbsp
          <%= @pre_answer.created_at.strftime('%Y/%m/%d') %>
        <% end %>
        </td>
      </tr>
      
      <% @questions.zip(@answer_keys).each do |question, answer_key| %>
      <tr>
        <td><%= question %></td>
        <td class="rm_number">
          <%= @answer.send(answer_key) %>
        </td>
        <td class="rm_number">
        <% if @pre_answer %>
          <%= @pre_answer.send(answer_key) %>
        <td>
          <% if @answer.send(answer_key).delete("^0-9").to_i < @pre_answer.send(answer_key).delete("^0-9").to_i %>
            <span>!!</span>
          <% elsif @answer.send(answer_key).delete("^0-9").to_i > @pre_answer.send(answer_key).delete("^0-9").to_i %>
            <span>gud</span>
          <% end %>
        </td>
        <% end %>
        </td>
      </tr>
      <% end %>

    </tbody>
  </table>
</div> 

app/views/admin/users/index.html.erb
<div class="col-md-4 offset-md-2 ">
<h5>患者一覧</h5>
  <table class="table table-striped table-hover">
    <thead class="thead-light">
      <tr>
        <th>患者ID</th>
        <th>氏名</th>
      </tr>
    </thead>
  
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, admin_user_path(user) %></td>
        <td><%= link_to (user.last_name + "　" + user.first_name), admin_user_path(user) %></td>
      </tr>
      <%  end %>
    </tbody>
  </table>
  <%= paginate @users %>
</div> 

app/views/admin/users/show.html.erb
<div class="col-md-5 offset-md-2">

<% if flash[:success] %>
  <p class="alert alert-warning h4 mt-2"><%= flash[:success] %></p>
<% end %>

<h5>患者詳細</h5>
  <h6>患者ID：<span><%= @user.id %></span></h6>
  <h6>氏　名：<span><%= @user.last_name + " " + @user.first_name %></span></h6>
  <table class="table">
    <thead class="thead-light">
      <tr><th></th><th>回答日時</th><th class="w-5"></th></tr>
    </thead>
  
    <tbody>
      <% @user.answers.order(id: :desc).each.with_index(1) do |answer, i| %>
      <tr>
        <td><%= i %></td>
        <td>
          <%= link_to user_admin_answer_path(answer.user_id, answer) do %>
            <%= answer.created_at.strftime('%Y/%m/%d  %H:%M') %>
          <% end %>  
        </td>
        <td>
          <%= link_to '削除', user_admin_answer_path(answer.user_id, answer), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-sm" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div> 

app/views/answers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-md-8 col-lg-7 offset-md-1 bg-light">
      <h6 class="my-4">こちらは増田歯科のWEB問診ページです</h6>
      
      <% if @answer.errors.any? %>
        <div class="alert alert-warning">
          <%= @answer.errors.count %>件エラーの発生しました
          <ul>
          <% @answer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with(model:[@user, @answer], local: true) do |f| %>
        <div class="question">
          Q1.目がよく疲れる
        </div>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q1"><%= f.radio_button :a1, "1 はい", name:"a1" %>はい</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q1"><%= f.radio_button :a1, "2 時々", name:"a1" %>時々</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-2 bg-color q1"><%= f.radio_button :a1, "3 いいえ", name:"a1" %>いいえ</label>

        <div class="question">
          Q2.口内炎ができる
        </div>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q2"><%= f.radio_button :a2, "1 はい", name:"a2" %>はい</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q2"><%= f.radio_button :a2, "2 時々", name:"a2" %>時々</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q2"><%= f.radio_button :a2, "3 いいえ", name:"a2" %>いいえ</label>
          
        <div class="question">
          Q3.下痢をしやすい
        </div>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q3"><%= f.radio_button :a3, "1 はい", name:"a3" %>はい</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q3"><%= f.radio_button :a3, "2 時々", name:"a3" %>時々</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q3"><%= f.radio_button :a3, "3 いいえ", name:"a3" %>いいえ</label>
        
        <div class="question">
          Q4.歯磨きの際に歯茎から血が出る
        </div>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q4"><%= f.radio_button :a4, "1 はい", name:"a4" %>はい</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q4"><%= f.radio_button :a4, "2 時々", name:"a4" %>時々</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q4"><%= f.radio_button :a4, "3 いいえ", name:"a4" %>いいえ</label>
          
        <div class="question">
          Q5.毎日の気分は？
        </div>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q5"><%= f.radio_button :a5, "1 優れない", name:"a5" %>優れない</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q5"><%= f.radio_button :a5, "2 あまり優れない", name:"a5" %>あまり優れない</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q5"><%= f.radio_button :a5, "3 平凡", name:"a5" %>平凡</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q5"><%= f.radio_button :a5, "4 ほぼ充実", name:"a5" %>ほぼ充実</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q5"><%= f.radio_button :a5, "5 充実", name:"a5" %>充実</label>

        <div class="question">
          Q6.食べ物が喉や胃にもたれる
        </div>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q6"><%= f.radio_button :a6, "1 はい", name:"a6" %>はい</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q6"><%= f.radio_button :a6, "2 時々", name:"a6" %>時々</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q6"><%= f.radio_button :a6, "3 いいえ", name:"a6" %>いいえ</label>
          
        <div class="question">
          Q7.尿の回数が増えた
        </div>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q7"><%= f.radio_button :a7, "1 はい", name:"a7" %>はい</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q7"><%= f.radio_button :a7, "2 少し", name:"a7" %>少し</label>
          <label class="target col-md-5 d-block border border-secondary rounded-pill mb-3 bg-color q7"><%= f.radio_button :a7, "3 いいえ", name:"a7" %>いいえ</label>
        
        <div class="form-group">
          <%= f.submit '送信', class:"form-control btn submit btn-lg btn-block btn-info mt-4" %>
        </div>
      <% end %>


    </div>
  </div>
</div>

<table>
  <div id="page-contact"><a href="/contacts/new"></a>ペヤング</div>
  <p onclick='window.location="/contacts/new"', role="link", class="contact-page">りんくーーーー</p>
</table>

app/views/answers/show.html.erb
<div class="col-md-6 offset-md-2">
  <p class="alert alert-success h4 mt-2">
    <%= flash[:success] %>
  </p>
</div>

  

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>


<tr onclick='window.location="/admin/contacts"', role="link", class="contact-page">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PerfectTeeth</title>
    <%= csrf_meta_tags %>
    
    <script src="https://kit.fontawesome.com/79e8119200.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-dark">
        <div class="navbar-header col-xs-4">
          <i class="fas fa-tooth"></i>
          <a class="navbar-brand p-2" hred="#"></a>
          <%= link_to "/users/sign_in", style:"text-decoration:none" do %>
            <span id="title">Perfect Teeth</span>
          <% end %>
        </div>
        <div class="col-xs-8">
          <ul class="nav navbar navbar-right">
            <li class="navbar-text">増田歯科・矯正歯科</li>
            <% if user_signed_in? %>
            <li class="pl-3">
              <%= link_to "終了", destroy_user_session_path, method: :delete %>
            </li>
              <% if current_user.admin? %>
                <li class="pl-3"><%= link_to "回答一覧", admin_answers_path %></li>
                <li class="pl-3"><%= link_to "患者一覧", admin_users_path %></li>
              <% end %>
            <% else %>
            <li class="pl-3">
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li class="pl-3">
              <%= link_to "ログイン", new_user_session_path %>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="box1"></div>
      <%= yield %>
    <script src="jquery.min.js"></script>
    <script src="js/my_jquery.js"></script>
    </main>
  </body>
</html>